apiVersion: v1
kind: Secret
metadata:
  name: demo-app-secrets
  namespace: demo-app
type: Opaque
stringData:
  keycloak-admin-password: "hackathon-demo-keycloak-admin"
  postgres-password: "hackathon-demo-postgres-password"